// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi9oaCs__Dweep2xlNXneeTZIPiN-ojZQ',
    appId: '1:671706734489:web:eabfa80f8abb06cf333d08',
    messagingSenderId: '671706734489',
    projectId: 'todo-app-55fc9',
    authDomain: 'todo-app-55fc9.firebaseapp.com',
    storageBucket: 'todo-app-55fc9.firebasestorage.app',
    measurementId: 'G-KR0HB8QMX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF8_L0E59nBvDnO7eJwcrONgMjOYBY73c',
    appId: '1:671706734489:android:dafc3194cf1e0899333d08',
    messagingSenderId: '671706734489',
    projectId: 'todo-app-55fc9',
    storageBucket: 'todo-app-55fc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkqaVnTqfVYygkMNXl-XkksyFOEY2AA5I',
    appId: '1:671706734489:ios:cce4cc333545c876333d08',
    messagingSenderId: '671706734489',
    projectId: 'todo-app-55fc9',
    storageBucket: 'todo-app-55fc9.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkqaVnTqfVYygkMNXl-XkksyFOEY2AA5I',
    appId: '1:671706734489:ios:cce4cc333545c876333d08',
    messagingSenderId: '671706734489',
    projectId: 'todo-app-55fc9',
    storageBucket: 'todo-app-55fc9.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi9oaCs__Dweep2xlNXneeTZIPiN-ojZQ',
    appId: '1:671706734489:web:cf2063862bcc7556333d08',
    messagingSenderId: '671706734489',
    projectId: 'todo-app-55fc9',
    authDomain: 'todo-app-55fc9.firebaseapp.com',
    storageBucket: 'todo-app-55fc9.firebasestorage.app',
    measurementId: 'G-Y2SS29Y1JC',
  );
}
